### PR TITLE
Return response in the end of recording

### PR DESCRIPTION
**Pull request by PaulWasTaken**
I have also removed `drain()`, `write_eof` since aiohttp does it

### CODE REVIEW

**Comment by PaulWasTaken** [comment]
#6

**Comment by mosquito** [comment]
@PaulWasTaken so [last commit](https://github.com/mosquito/aiohttp-asgi/commit/9d094478fd91bda4651e7597fc789066ac7620d9) brings the test for chunked ASGI responses, It's a part of the spec. So I guess this PR is incompatible with them.

**Comment by PaulWasTaken** [comment]
I have updated the code and tests pass

**Comment by PaulWasTaken** [comment]
@mosquito

**Comment by mosquito** [comment]
Released in 0.4.0, sorry for the delay.

**Pull request merged**
